---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: todo-app
  namespace: default
  labels:
    app: todo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-app
  template:
    metadata:
      labels:
        app: todo-app
    spec:
      containers:
      - name: todo-app
        image: "sach149/todo-app:DOCKER_IMAGE_TAG"
        ports:
          - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: todo-app
  namespace: default
spec:
  selector:
    app: todo-app
  type: LoadBalancer
  ports:
  - name: http
    targetPort: 3000
    port: 80